# Four stages, so the runtime image carries neither Node nor a package manager,
# and the PHP extensions are compiled once rather than per stage.
#
# The asset build needs PHP, which is not obvious. resources/js/actions and
# resources/js/routes are generated by Wayfinder's Vite plugin, which shells
# out to `php artisan wayfinder:generate` and therefore needs a bootable
# application with its vendor directory present. A Node-only stage fails here.
#
# Nothing writes to a volume: the logo is fetched from a URL and kept in the
# database (SPEC §6), so the container filesystem is genuinely disposable and
# Postgres is the only thing that survives a deploy.

# ------------------------------------------------------------------ base ----
FROM dunglas/frankenphp:1-php8.4 AS base

RUN install-php-extensions pdo_pgsql pgsql intl zip opcache gd bcmath

WORKDIR /app

# ---------------------------------------------------------------- vendor ----
FROM composer:2 AS vendor

WORKDIR /app

COPY composer.json composer.lock ./

# Scripts are skipped because artisan needs the whole application, which is not
# here yet. package:discover runs in the runtime stage instead.
RUN composer install \
      --no-dev \
      --no-scripts \
      --no-interaction \
      --prefer-dist \
      --optimize-autoloader

# ---------------------------------------------------------------- assets ----
FROM base AS assets

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

# Dependencies before source, so a commit that changes neither lockfile reuses
# this layer instead of reinstalling everything.
COPY package.json package-lock.json ./
RUN npm ci

COPY --from=vendor /app/vendor ./vendor
COPY . .

# Wayfinder boots the application to read the routes. It never touches the
# database, but Laravel refuses to boot without a key, so this is a throwaway
# one that lives for the length of this stage and reaches no runtime image.
RUN cp .env.example .env && php artisan key:generate

# Read by Vite at build time, so a runtime environment variable would never
# reach it. Only the browser tab title depends on it, but it is one line.
ARG VITE_APP_NAME=Xoloff
ENV VITE_APP_NAME=$VITE_APP_NAME

# build, never build:ssr. config/inertia.php sets ssr.enabled => true with no
# SSR bundle, which is harmless only while no bundle exists: the moment one
# appears at bootstrap/ssr/ssr.mjs the guard stops firing and every page load
# POSTs to 127.0.0.1:13714, where nothing is listening.
RUN npm run build

# --------------------------------------------------------------- runtime ----
FROM base AS runtime

# The base image healthchecks Caddy's admin endpoint on :2019. kamal-proxy
# probes /up itself, and a container reporting unhealthy is one Kamal will
# replace mid-deploy for no reason.
HEALTHCHECK NONE

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY --chown=www-data:www-data . .
COPY --from=vendor --chown=www-data:www-data /app/vendor ./vendor
COPY --from=assets --chown=www-data:www-data /app/public/build ./public/build

RUN composer dump-autoload --no-dev --optimize --classmap-authoritative \
    && php artisan package:discover --ansi \
    && rm /usr/bin/composer

COPY docker/entrypoint.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

ENV SERVER_NAME=:80

EXPOSE 80

ENTRYPOINT ["entrypoint"]
CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
